version: '3.8'
services:
  app:
    build: ./
    image: wallet
    container_name: wallet
    restart: on-failure
    ports:
      - "8080:8080"

    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres